language: php
php:
  - 7.0
  - 5.6
  - 5.5
env:
  - PHP_VERSION=`phpenv version | sed "s/ (.*//g"`
before_install:
  - phpenv version
install:
  - if [ $PHP_VERSION == "7.0" ]; then pecl install Weakref; else pecl install Weakref-0.2.6; fi
  - phpenv rehash
  - composer install
branches:
  only:
    - master
    - /^\d+\.\d+\.x$/
